#!/usr/bin/tclsh
package require Tk

# I am generating scripts to render documents.
# This would be the "library"/predefined part

set widget_accumulator 0
proc my_paragraph {text} {
    set name ".paragraph${::widget_accumulator}"
    incr ::widget_accumulator

    # NOTE: it is a `text`, because I'm utalizing tags
    text $name \
        -background [. cget -background] \
        -borderwidth 0 \
        -highlightthickness 0 \
        -wrap word \
        -height 5
        # the widget will take up exactly 3 lines,
        #  even tho (on my system) 2 are enough.
        # setting it lower could crop the text

    $name insert end $text

    pack $name -side top
}

wm title . "example"
bind . <Destroy> {exit}

# This would be the script generated by another program
my_paragraph {Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.}
my_paragraph {Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.}

puts [ .paragraph0 count -update -displaylines 1.0 end ]
